# Generated by Django 5.0.1 on 2024-01-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namecountry', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
